apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: my-application-1
    appstudio.openshift.io/component: go-application
    build.appstudio.openshift.io/component: go-application
    pipelines.appstudio.openshift.io/type: build
  name: go-application-on-push
  namespace: karthik-jk
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-appstudio/user-workload:{{revision}}
  - name: path-context
    value: .
  - name: dockerfile
    value: Dockerfile
  pipelineRef:
    bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
    name: docker-build
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: appstudio
    subPath: go-application-on-push-{{revision}}
  - name: registry-auth
    secret:
      secretName: redhat-appstudio-registry-pull-secret
status: {}
